# config for https://github.com/mgechev/revive
ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = 1
warningCode = 0

[directive.specify-disable-reason]
severity = "error"

[rule.exported] # require docs
